export const ATTEMPT_LOGIN = "ATTEMPT_LOGIN";
export const ATTEMPT_REGISTER = "ATTEMPT_REGISTER";
//
export const WINDOW_RESIZE = "WINDOW_RESIZE";
//
export const QUERY_STOCKS = "QUERY_STOCKS";
export const UPDATE_PREVIEW_CHART = "UPDATE_PREVIEW_CHART";
export const QUERY_ALL_SYMBOLS = "QUERY_ALL_SYMBOLS";
export const QUERY_MARKETS = "QUERY_MARKETS";
export const QUERY_ALL_NEWS = "QUERY_ALL_NEWS";
//
